apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  # value should be base64 encoded 
  # command => echo -n 'value' | base64
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
